# Generated by Django 3.2.5 on 2021-07-18 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210718_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='image',
            new_name='image_food',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='image',
            new_name='image_restaurant',
        ),
    ]
