# Generated by Django 3.2.5 on 2021-07-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20210718_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
