# Generated by Django 3.2.5 on 2021-07-23 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_food_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='food',
        ),
    ]
