# Generated by Django 3.2.5 on 2021-07-23 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_remove_comment_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='restaurant.restaurant'),
        ),
    ]
